Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
a.ndim #dimensions

1

In [7]:
b.ndim #dimension

2

In [8]:
b.shape #rows and columns

(2, 4)

In [9]:
b.dtype #dataype

dtype('int32')

In [10]:
a.itemsize #size 

4

In [11]:
a.nbytes #bytes

16

In [12]:
c = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
c

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [13]:
c[1,1]

2

In [14]:
c[1,2]

3

In [15]:
c[0,:] #total row

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
c[:,2] #total column

array([3, 3])

In [19]:
d = np.array([[[1,2],[2,3],[3,4],[5,6]]])
d

array([[[1, 2],
        [2, 3],
        [3, 4],
        [5, 6]]])

In [20]:
d.ndim

3

In [21]:
s = np.zeros((2,3))
s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
s = np.ones((2,3))
s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
d = np.full((2,3),99)
d

array([[99, 99, 99],
       [99, 99, 99]])

In [24]:
f = np.random.rand(4,2)
f

array([[0.93303594, 0.45625248],
       [0.17767384, 0.58408072],
       [0.34736862, 0.51732811],
       [0.71868708, 0.01523367]])

In [25]:
c = np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 12
a

array([1, 2, 3, 4])

In [27]:
b

array([12,  2,  3,  4])

In [28]:
a+2

array([3, 4, 5, 6])

In [29]:
a-2

array([-1,  0,  1,  2])

In [30]:
a**2

array([ 1,  4,  9, 16])